### ISSUE TITLE
Project can't be opened in Unity

### ISSUE THREAD

**Issue by Pflegusch** [Wally869/TutorialPlatformer2D#1]
Hi, 

I am having problems starting the project in Unity with version 2019.4.40f1.  Below you can find a screenshot of the error messages. Is there anything I can do or can you help me to fix this? Would be really appreciated! :) 
![grafik](https://user-images.githubusercontent.com/44372539/175997698-aa76c7ff-0ad0-46ae-89e0-1597941766e7.png)

**Comment by Wally869** [comment]
I think you might be missing some dependencies, I think the GridBrush was an external import.

I'll try to update the project and project and provide it as a package, to make it easier to use

**Comment by Pflegusch** [comment]
That would be really, really nice! Couldn't get it to work but would still love to try it out :)

**Comment by Wally869** [comment]
I've updated the project to use Unity 2021.3, and published code and assets in a .unitypackage file in releases
You can get it here: https://github.com/Wally869/TutorialPlatformer2D/releases/tag/Package

Let me know if it works!

**Comment by Wally869** [comment]
It runs fine in the Editor, and I've put all assets in the package so it should be good to go

**Comment by Pflegusch** [comment]
It still is not working sadly, what are the steps you did to let it run in the editor? I simply tried to create new 3D project and then imported the .unitypackage file, hoewever, I'm still getting compiler errors :( 
![grafik](https://user-images.githubusercontent.com/44372539/182575299-5a64c2d3-9177-44dd-9159-3517a63e832c.png)

**Comment by Pflegusch** [comment]
Nevermind, obviously I should have created a new 2D project. My bad. Thank you very much!

**Comment by Wally869** [comment]
Thanks for the update, I'll add a note to the readme
